version: '3.1'

services:

  postgres:
    container_name: job-rotation-postgres
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - /c/Volumes/job/job-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.15-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - /c/Volumes/job/job-rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672